version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tarot
      POSTGRES_USER: tarot_user
      POSTGRES_PASSWORD: tarot_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://tarot_user:tarot_pass@db:5432/tarot
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env # Load environment variables from .env file

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
